# SPDX-License-Identifier: MIT
---
- name: Kopia Role | Installation
  ansible.builtin.include_tasks: install.yml
  when: kopia_state == 'present'

- name: Kopia Role | Uninstallation
  ansible.builtin.include_tasks: uninstall.yml
  when: kopia_state == 'absent'
